name: Build project and publish to NPM

inputs:
  vars:
    description: All the vars
    required: true
  secrets:
    description: All the secrets
    required: true

runs:
  using: composite

  steps:
    - name: Dump GitHub context
      shell: bash
      run: |
        cat << EOF
        ${{ toJSON(github) }}
        EOF

    - name: Dump secrets
      shell: bash
      run: |
        cat << EOF
        ${{ toJSON(fromJSON(inputs.secrets)) }}
        EOF

    - name: Dump vars
      shell: bash
      run: |
        cat << EOF
        ${{ toJSON(fromJSON(inputs.vars)) }}
        EOF
