name: Build and publish on release publication

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Dump via action
        uses: KDean-Dolphin/TestGitHub/.github/actions/whatever@main
        with:
          secrets: ${{ toJSON(secrets) }}
          vars: ${{ toJSON(vars) }}
